### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [wseemann/RoMote#29]
The `com.google.android.gms:play-services-oss-licenses` is not FOSS. Could you please choose an alternative from [here](https://gitlab.com/-/snippets/1896503)? Thanks!

**Comment by wseemann** [comment]
How is this not open source? The source code for this plugin can be found
here, licensed under the Apache License version 2:

https://github.com/google/play-services-plugins

- William

**Comment by wseemann** [comment]
I appreciate you letting me know about this issue. I reviewed the link you
sent and see that F-Droid prohibits use of this library despite it being
open source. Respectfully, I do not wish to participate in Open Source
elitism or perpetuate the idea that someone's work is not considered Open
Source just because they use a third party dependency that is deemed
proprietary. I will not be updating the app to use one of the alternatives.
If the F-Droid maintainers have an issue with this they can remove my app.
Thanks again for filing the ticket.

**Comment by linsui** [comment]
https://github.com/google/play-services-plugins is the source code of the plugin, i.e.`com.google.android.gms.oss-licenses-plugin`. However, the `com.google.android.gms:play-services-oss-licenses` lib is not open spurce.
