### ISSUE TITLE
Romote not working

### ISSUE THREAD

**Issue by Nekuzar** [wseemann/RoMote#40]
I bought a new Roku Express (1080p), Romote was working until I updated Roku. I tried with 2 smartphones, it can pair with Roku normally but is not working.

**Comment by Nekuzar** [comment]
I dont know what happened with the update but I changed the network access of mobile apps and is working now. (First time using Roku)

**Comment by terenc3** [comment]
Had the same problem that it stopped working some day. According to https://www.evolved-home.com/roku-14-1-update-and-loss-of-device-control/ Update 14.1 sets network access to restrictive as default. So you need to enable access, see https://support.roku.com/article/217288467.

@wseemann maybe you can add a note to the readme. It was difficult to diagnose because the app connected correctly and I was even able to use the channels tab, but nothing on the remote tab was working

**Comment by wseemann** [comment]
> Had the same problem that it stopped working some day. According to https://www.evolved-home.com/roku-14-1-update-and-loss-of-device-control/ Update 14.1 sets network access to restricted as default. So you need to enable access, see https://support.roku.com/article/217288467.
> 
> @wseemann maybe you can add a note to the readme. It was difficult to diagnose because the app connected correctly and I was even able to use the channels tab, but nothing on the remote tab was working
> 
> Model: 3930EU - Roku Express Version: 14.1 Build: 4.7708-AE

I'll add information to the README, thank you for the link @terenc3.
